---
title: "Welcome to NPHD9040"
author: "Dr. Joshua Lambert"
output: html
format:
  html:
    toc: true
    toc-title: "Topics"
    css: styles.css
---

# Situations and ANOVA Appropriateness

For each of the following situations, indicate whether ANOVA is appropriate or not appropriate. Please justify your answer with one to two sentences.

1. The independent variable (IV) is age group--people in their 60s, 70s, and 80s; the dependent variable (DV) is health-related hardiness, as measured on a 20-item scale.

2. The IVs are ethnicity (White, African American, Hispanic, and Asian) and birthweight status (< 2500 grams vs. 2500 grams); the DV is serum bilirubin levels.

3. The IV is maternal breastfeeding status (breastfeeds vs. does not breastfeed); the DV is maternal bonding with infant, as measured on a 10-item self-report scale.

4. Suppose we wanted to compare the somatic complaints (as measured on a scale known as the Physical Symptom Survey or PSS) of three groups of people: nonsmokers, smokers, and people who recently quit smoking. Using the following data for PSS scores, do a one-way ANOVA to test the hypothesis that the population means are equal:

    - Input these data into JMP. What are the means for the three groups? Conduct an ANOVA and compute the sums of squares, degrees of freedom, and mean squares for these data. What is the value of F? Using an alpha of .05, is the F statistically significant? Summarize this information in both words and in an ANOVA table.

5. Using the data from Question 4, compute three t-tests to compare all possible pairs of means with the Bonferroni method with a family-wise α = .05. Which pairs are significantly different from one another, using this multiple comparison procedure? Also complete a contrast for testing if Nonsmokers are different from ever Smoking. What is the Null and Alternative Hypothesis for this test? What is the P-value for this contrast? Compare this result to α = .05. What is the result and interpretation?
